### ISSUE TITLE
Error on npm run docker:up

### ISSUE THREAD

**Issue by drew12341** [m4heshd/ufc-ripper#1]
Hi - I get the following when running the above command:

 => ERROR [ufc-ripper 3/4] COPY ./package/linux/ .                                                                                                 0.0s
------
 > [ufc-ripper 3/4] COPY ./package/linux/ .:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref 98e1218d-1a44-4833-9dbc-47e781718f5d::itwb4qlmgbpav4pmx4gkksgxp: failed to walk /var/lib/docker/tmp/buildkit-mount2982520804/package: lstat /var/lib/docker/tmp/buildkit-mount2982520804/package: no such file or directory

**Comment by m4heshd** [comment]
Oh, I think this should be an addition to the documentation.

You need to run `npm run pack-linux` before building the docker image because the Dockerfile needs to copy over the Linux binary.

**Comment by drew12341** [comment]
Thanks!
