### ISSUE TITLE
Audio Splitting from Video

### ISSUE THREAD

**Issue by FylnnLives** [m4heshd/ufc-ripper#12]
Audio not merging with video file after being converted. I have uninstalled and re-downloaded but still having the same issue. Worked fine for over 4 weeks but hasn't worked for the last 2 weeks. Thanks

![Screenshot 2024-09-19 202500](https://github.com/user-attachments/assets/9ec64e62-084c-4311-8f7c-21e0f030fc53)

**Comment by m4heshd** [comment]
Are there any errors in the console? 

Also, check if you have enough space in the destination storage you selected as the download path. Technically, you require double the size of the video you're downloading since it needs to be merged as a separate file.

**Comment by FylnnLives** [comment]
Hi, Thank you for the quick reply and your work on this.

No error messages on console and 700gb free on the ssd drive it's going to. Just weird how it was working, then stopped. No update on the pc which have affected it. Thanks

**Comment by m4heshd** [comment]
@FylnnLives My apologies for abandoning this issue. I went on vacation and completely forgot about this. If I may ask, what was the issue actually?

**Comment by FylnnLives** [comment]
I'm sorry for the seriously later reply. Just purged my e-mails and saw you had replied. I just uninstalled it and left it for weeks and tried again and this time it worked. I think one of the third party downloads you do in the install had an issue. It worked perfectly fine, then it didn't. Think something else I had might of corrupted a file or something. Thanks again for the Ripper, it's a God send
