### ISSUE TITLE
UFC Fight Pass RIPPER giving error while downloading videos date 2019 and under.

### ISSUE THREAD

**Issue by NoStressMate44** [m4heshd/ufc-ripper#2]
So i wanna download ufc fight pass videos, the ones that are made under 2019 and below is giving a error.

This video for example: https://ufcfightpass.com/video/64369/dustin-poirier-vs-justin-gaethje-ufc-fight-night

![image](https://github.com/m4heshd/ufc-ripper/assets/139411799/b4c2ac60-0c43-4599-80ab-4f2172e0d253)
![image](https://github.com/m4heshd/ufc-ripper/assets/139411799/b7987678-cd66-433f-a120-d61078bcc2bd)

**Comment by m4heshd** [comment]
Hi @NoStressMate44,

I just checked and it downloads perfectly fine for me.
![image](https://github.com/m4heshd/ufc-ripper/assets/6711514/9124622c-ac22-4245-88e1-b1117e543922)


Can you show me the `Video` section of your configuration?

**Comment by NoStressMate44** [comment]
yes one sec
[cid:775e96fe-57cd-4c4d-8143-33a8613ccb51][cid:d578d917-297a-430c-873a-c9047d0b9325]
________________________________
Van: Mahesh Bandara Wijerathna ***@***.***>
Verzonden: donderdag 13 juli 2023 03:00
Aan: m4heshd/ufc-ripper ***@***.***>
CC: NoStressMate44 ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [m4heshd/ufc-ripper] UFC Fight Pass RIPPER giving error while downloading videos date 2019 and under. (Issue #2)


Hi @NoStressMate44<https://github.com/NoStressMate44>,

I just checked and it downloads perfectly fine for me.
[image]<https://user-images.githubusercontent.com/6711514/253131636-9124622c-ac22-4245-88e1-b1117e543922.png>

Can you show me the Video section of your configuration?

**Comment by NoStressMate44** [comment]
![image](https://github.com/m4heshd/ufc-ripper/assets/139411799/41bb662d-497e-4885-bee8-67b7419356fe)
![image](https://github.com/m4heshd/ufc-ripper/assets/139411799/13ff989a-84fe-41a9-bd26-7918d16e5ab9)

**Comment by m4heshd** [comment]
Ok. Found the issue. Apparently, some older videos in the Fight Pass library don't have 1080p streams. Your best option is to go with 720p.

Here's some more context about that specific video with stream metadata.

![image](https://github.com/m4heshd/ufc-ripper/assets/6711514/1498113d-ed3a-4068-9a8a-8fdc1fd51f53)

There are your only options.

**Comment by NoStressMate44** [comment]
ah okay, so that was the problem :/. Those videos who all are in fightpass they are nowhere to be found better with high quality right? fightpass is the best what you can find? quality

**Comment by m4heshd** [comment]
Yes. Fight Pass is the original source. So that's the best you can get.

**Comment by NoStressMate44** [comment]
So you wont fight higher quality on youtube? And also i have this FlowFrames application, it converts all the videos from 30fps to 60fps with AI, Crazy

**Comment by m4heshd** [comment]
> So you wont fight higher quality on youtube?

I don't think so because it's illegal to do so.

**Comment by NoStressMate44** [comment]
Gaethje vs Barboza is 1080p on youtube, but 720p on fight pass?

**Comment by m4heshd** [comment]
Oh, you mean the ones uploaded by UFC themselves, right? Yeah, that could be. They might have higher-resolution sources but don't care enough to add those to the Fight Pass. Who knows. 🤷🏽

**Comment by NoStressMate44** [comment]
yea, but the 1080p ones ill download from ripper in fightpass, and the fights in 1080p on youtube ill download them on youtube. but there are some clips which are not on youtube. i need them the most so, ill let you know
