### ISSUE TITLE
Aria2c Support

### ISSUE THREAD

**Issue by Dot50Cal** [m4heshd/ufc-ripper#3]
Hey there,

I love this tool and wanted to thank you for implementing it. I also wanted to put in a feature request. This technically isn't a bug, but by default, YT-DLP supports using an external downloader. The one that seems most common is Aria2c:

https://github.com/ytdl-org/youtube-dl/issues/26793

This can be used by pushing the following arguments to ytdlp.exe:

--external-downloader aria2c

I have tried tossing the aria2c.exe into the bin folder, and added --external-downloader aria2c to the config.json dlArgs, but this does not work and I believe there is some back-end work that needs to be done to allow/recognize aria2c.

Would this be something you would implement? It would make the downloads go extremely quick, as it utilizes multiple threads to download the fragments rather than 1 at a time like YTDLP does. This would be the difference between a 1 minute download and a 15 minute one for me personally when I have tested in the past.

Thank you again!

**Comment by m4heshd** [comment]
I have absolutely no idea how I missed an issue opened two months back. So, sorry about the delayed response.

The improvement you suggested is definitely worth considering as it can significantly reduce the download time. I will review it in detail.

**Comment by m4heshd** [comment]
I have investigated the feature you requested and found that using `aria2` for downloads does not allow `ufc-ripper` to read the download progress from stdout. This limitation is confirmed in https://github.com/yt-dlp/yt-dlp/issues/2038. 

However, I have implemented an alternative solution by adding the support for `--concurrent-fragments` feature in ad7ba02f9291e2a37ad834d190d77da4ef147684 and a4ab509a68ee0cd348a13f95d7d51d5b0054b596 which is native for `yt-dlp`. The usage can be configured via the configurations UI. I've been using around `200` concurrent fragments, and the downloads were blazing fast.

This feature is now available in [`v1.2.0`](https://github.com/m4heshd/ufc-ripper/releases/tag/v1.2.0). Thank you for suggesting this enhancement.

**Comment by Dot50Cal** [comment]
> I have investigated the feature you requested and found that using `aria2` for downloads does not allow `ufc-ripper` to read the download progress from stdout. This limitation is confirmed in [yt-dlp/yt-dlp#2038](https://github.com/yt-dlp/yt-dlp/issues/2038).
> 
> However, I have implemented an alternative solution by adding the support for `--concurrent-fragments` feature in [ad7ba02](https://github.com/m4heshd/ufc-ripper/commit/ad7ba02f9291e2a37ad834d190d77da4ef147684) and [a4ab509](https://github.com/m4heshd/ufc-ripper/commit/a4ab509a68ee0cd348a13f95d7d51d5b0054b596) which is native for `yt-dlp`. The usage can be configured via the configurations UI. I've been using around `200` concurrent fragments, and the downloads were blazing fast.
> 
> This feature is now available in [`v1.2.0`](https://github.com/m4heshd/ufc-ripper/releases/tag/v1.2.0). Thank you for suggesting this enhancement.

Thanks so much for this! I'll get back on my archiving project now :) Just tested it and speeds are so much faster, thanks very much for doing this!
