### ISSUE TITLE
"Invalid URL"

### ISSUE THREAD

**Issue by throwaway45632** [m4heshd/ufc-ripper#6]
I was using UFC Ripper yesterday and it was working fine, this morning I'm entering standard download links and it says "Invalid URL" for all of them.

![Screenshot 2023-10-02 105245](https://github.com/m4heshd/ufc-ripper/assets/110213411/68608d8d-a4b6-4791-b0d3-54ddee1369f2)

Example, download link for UFC 1: The Beginning

https://ufcfightpass.com/video/30323?playlistId=2524

**Comment by throwaway45632** [comment]
Thank you very much for the fast turn around, this problem has been fixed for me. Also thank you for making this useful app :-)

**Comment by m4heshd** [comment]
@throwaway45632 You're welcome. The version `1.1.2` was rendered to be broken in the build. Please use [`v1.1.3`](https://github.com/m4heshd/ufc-ripper/releases/tag/v1.1.3).
